# Generated by Django 3.2.5 on 2021-07-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('userId', models.IntegerField()),
                ('date', models.DateField()),
                ('timeFrom', models.TimeField()),
                ('timeTo', models.TimeField()),
                ('totalMinutes', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Totp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('secret', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('hourlyRate', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('routingNumber', models.CharField(max_length=30)),
                ('accountNumber', models.CharField(max_length=30)),
            ],
        ),
    ]
