# Generated by Django 3.2.5 on 2021-07-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='chargeToClientRate',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=6),
            preserve_default=False,
        ),
    ]
